version: '3'
services:
  redis:
    image: bitnami/redis
    logging:
        driver: json-file
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password123
    volumes:
      - /bitnami/redis/data
  signatory:
    image: ecadlabs/signatory:latest
    logging:
        driver: json-file
    ports:
      - 6732:6732
    volumes:
      - ./signatory.yaml:/etc/signatory.yaml
      - ./key_gen_funder.key:/etc/key_gen_funder.key
networks:
  default:
    external: true
    name: bridge
